### ISSUE TITLE
ModuleNotFoundError: No module named 'OverfitShapes' after successfully building

### ISSUE THREAD

**Issue by anticdimi** [nathanrgodwin/overfit-shapes#6]
Hi @nathanrgodwin,

I followed instructions for installation, and after some cpp hacking, I managed to `make` the package.
Conversely, I get the following error:
```
File "some_path/overfit-shapes/OverfitShapes/train.py", line 4, in <module>
    from NeuralImplicit import NeuralImplicit
  File "some_path/overfit-shapes/OverfitShapes/NeuralImplicit.py", line 10, in <module>
    from OverfitShapes import PointSampler, MeshLoader, normalizeMeshToSphere
ModuleNotFoundError: No module named 'OverfitShapes'
```
Do you have any hints on how to solve this problem?
I am building the project on Ubuntu 22.04.

**Comment by anticdimi** [comment]
The folder `build/workspace/` contained the package.

But now the following error arrises:
```
Traceback (most recent call last):
  File "/home/dimi/Repositories/overfit-shapes/build/workspace/train.py", line 5, in <module>
    from OverfitShapes import Renderer, Camera
ImportError: cannot import name 'Renderer' from 'OverfitShapes' (/home/dimi/Repositories/overfit-shapes/build/workspace/OverfitShapes.cpython-310-x86_64-linux-gnu.so)
```
